<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="assets/lib/bootstrap/dist/css/bootstrap.css">
    <link rel="stylesheet" href="assets/css/main.css">
    <?php foreach ($view->getStylesheets() as $stylesheet) { ?>
        <link rel="stylesheet" href="<?= $stylesheet ?>">
    <?php } ?>
</head>

<body>
    <nav class="navbar fixed-top navbar-dark bg-dark">
        <a class="navbar-brand" href="#">FastChat</a>
    </nav>
    <?= $view->render() ?>
    <?php foreach ($view->getScripts() as $script) { ?>
        <script type="text/javascript" src="<?= $script ?>"></script>
    <?php } ?>
</body>

</html>
