<?php $view->addScript('assets/lib/blueimp-md5/js/md5.js'); ?>
<?php $view->addScript('assets/lib/dayjs/dayjs.min.js'); ?>
<?php $view->addScript('assets/js/chat.js'); ?>
<div class="container-fluid">
    <div class="row chat">
        <div class="col-8" id="messages">
            <ol></ol>
        </div>
        <div class="col border-left bg-light">
            <ul>
                <li>François</li>
                <li>Léonard</li>
                <li>Etienne</li>
                <li>Hugo</li>
            </ul>
        </div>
    </div>
</div>
<nav class="navbar fixed-bottom navbar-dark bg-dark">
    <form class="form-inline my-2 my-lg-0 w-100" method="POST" action="messages" id="message-form">
        <textarea class="form-control mr-sm-2  w-50" placeholder="Envoyer un message à tout le monde" name="content" rows="1"></textarea>
        <button class="btn btn-primary my-2 my-sm-0" type="submit">Envoyer</button>
    </form>
</nav>