version: "3.7"
services:
  php:
    build:
      dockerfile: .docker/services/php-apache/Dockerfile
      context: ..
    ports:
      - "${APP_PORT}:80"
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ../dump.sql:/tmp/dump.sql
volumes:
  mysql_data:
  composer_home: