version: "3.7"
services:
  php:
    build: ./services/php
    volumes:
      - ../:/app
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ../dump.sql:/tmp/dump.sql
  nginx:
    image: nginx:1.15
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ../:/app
      - ./services/nginx/site.conf:/etc/nginx/conf.d/default.conf
  composer:
    image: composer:1.8.5
    environment:
      - COMPOSER_HOME=/tmp/composer
    volumes:
      - ../:/app
      - composer_home:/tmp
    user: ${DEV_UID}:${DEV_GID}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOST=mysql
    ports:
      - "${PMA_PORT}:80"
volumes:
  mysql_data:
  composer_home: