version: "3.7"
services:
  app:
    image: registry.gitlab.factory.digiwin.tech/trsb/fastchat/app
    build:
      dockerfile: .docker/services/app/Dockerfile
      context: ..
    depends_on:
      - database
    volumes:
      - ../:/var/www/html
      - ../dump.sql:/tmp/dump.sql
    ports:
      - "${APP_PORT}:80"
  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ../dump.sql:/tmp/dump.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOST=database
    ports:
      - "${PMA_PORT}:80"
