<form method="POST">
    <div class="modal static-modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Identification</h5>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <input class="form-control" type="email" name="email" placeholder="Email">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="nickname" placeholder="Pseudo">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Connexion</button>
                </div>
            </div>
        </div>
    </div>
</form>
